version: "3.9"
services:
  web:
    build: .
    container_name: portfolio
    restart: always
    environment:
      SPOTIFY_CLIENT_ID: CLIENT_ID
      SPOTIFY_CLIENT_SECRET: CLIENT_SECRET
      SPOTIFY_REFRESH_TOKEN: REFRESH_TOKEN 
    ports:
      - "3000:3000"
